language: node_js
node_js: node
cache: npm
services:
- redis-server
script:
- npm run lint
- npm test
- npm run build
deploy:
  provider: heroku
  skip_cleanup: true
  app: unpkg
  api_key:
    secure: jpyZTuvJZpT9KfFLbKh7j1wVtl8zKvQY1yLwrsHgNl02RCLiBtcvRfWDU1GJl7FLI4DfeEbPFR1tM4xCSkHuDbTAKzVS/giAeNq/Q7B64dAwtvb4DwqNKUMb8ihj37pGImh3WpFQyoYb6bvAeLCJOvtVHkLVq/6X3B7pjKL2XKbaOFKkmcxZIaT41Im4BPmVkC0zrtgpWpz8i6IgxldweBC4km3vpQziY4JhoEWznW/l2PQ6LCeGRLeNZm0V/MXVNNFvh/fZyS/Oyba/a8B1u1H7DIEnBnVd7m0kry+xkQEd5M+m1qJQiQ99wwJ3inTIFK43dhlsM/AhueUb8RDABdNGm52Jy/iQ1r6eliZaxrBovOaH3uwW7Mxq8t30igTEZk7Qi74e46lcBN7ner/O+9hl8K72UPpXL3Y55wuZzMr+kOveuoRz7ancGJz1ovpw+uiM2LrEifuA9ehcBZ1vAgdJQw+vxTsV0a77WRQKFxByujzb7LtIYvVrCINYZNYYTf2V+hkyN/AMltdmrFyGr7agj8KO7jZMJniENLBdbYK9AfRzZMLRF1cwe47sG3IA9ROXEkrNLT/f410VABiBdh3+6Wu5AcLG/wLKTGZiFtwBQBXxCsvCnwYLKgmcWRNSxn4e2mvBRFepN6FDYeXXLXqV6FhsGUMKmDubhvqN2EI=
  on:
    branch: master
