runtime: nodejs10
env: standard
instance_class: F4
automatic_scaling:
  min_instances: 2
  max_instances: 12
  max_concurrent_requests: 20
  target_throughput_utilization: 0.6
  max_idle_instances: 2
