version: "3"

networks:
  localnet: {}

services:

  cache:
    image: redis
    volumes:
      - ./data:/data
    ports:
      - "6379:6379"
    networks:
      - localnet

  server:
    build: .
    image: server
    command: nodemon --ignore client server.js
    env_file: .env
    volumes:
      - .:/app
    depends_on:
      - cache
    ports:
      - "8080:5000"
    networks:
      - localnet

  worker:
    build: .
    image: worker
    command: nodemon --ignore client server/ingestLogs.js
    env_file: .env
    volumes:
      - .:/app
    depends_on:
      - cache
    networks:
      - localnet
